#!/usr/bin/env python3
"""ThumbnailImage, the magick script and Gio name a thumbnail the same.

Freedesktop thumbnails are named by the md5 of the file's uri, so the three places
that write or read them (ThumbnailImage.qml, generate-thumbnails-magick.sh and
thumbgen.py, which goes through Gio) must encode a path identically. They did not:
the script encoded `!` and `'`, encoded non-ASCII per character instead of per UTF-8
byte, and resolved symlinks; QML kept GLib's `$&+,=:@` escaped. Any such name had its
thumbnail written where nothing looked, and regenerated by ImageMagick every view.
The script also took the file name inside a bash -c string, so `'` broke it.

This evaluates the QML expression under node and the script's urlencode under bash,
and compares both with Gio for names that hit every difference.
"""
import json
import re
import subprocess
from pathlib import Path

II = Path(__file__).resolve().parent.parent / "dots/.config/quickshell/ii"
qml = (II / "modules/common/widgets/ThumbnailImage.qml").read_text()
script = II / "scripts/thumbnails/generate-thumbnails-magick.sh"

NAMES = ["/home/u/Pictures/Don't stop!.png", "/home/u/エヴァ 初号機.jpg", "/home/u/é%#?&.png",
         "/x/$a&b+c,d;e=f:g@h[i]{j}^k|l`m\"n<o>p\\q.png", "/plain/name.png"]

m = re.search(r"const parts = (.+?);\n", qml, re.S)
assert m, "ThumbnailImage.qml: no `const parts = ...;` expression to check"
expr = m.group(1)
js = ("const FileUtils = { trimFileProtocol: s => s.replace(/^file:\\/\\//, '') };"
      f"for (const sourcePath of JSON.parse(process.argv[1])) {{ const parts = {expr}; console.log('file://' + parts.join('/')); }}")
qml_uris = subprocess.run(["node", "-e", js, json.dumps(NAMES)], capture_output=True, text=True, check=True).stdout.splitlines()

fn = re.search(r"^urlencode\(\) \{.*?^\}", script.read_text(), re.S | re.M).group(0)
sh_uris = [subprocess.run(["bash", "-c", fn + '\necho "file://$(urlencode "$1")"', "_", n],
                          capture_output=True, text=True, check=True).stdout.strip() for n in NAMES]

gio = subprocess.run(["python3", "-c", "import sys\nfrom gi.repository import Gio\nfor n in sys.argv[1:]: print(Gio.File.new_for_path(n).get_uri())", *NAMES],
                     capture_output=True, text=True)
if gio.returncode == 0:
    for n, g, q, s in zip(NAMES, gio.stdout.splitlines(), qml_uris, sh_uris):
        assert q == g, f"ThumbnailImage.qml names {n!r} {q}, Gio {g}"
        assert s == g, f"generate-thumbnails-magick.sh names {n!r} {s}, Gio {g}"
else:
    print("note: no Gio here, comparing QML with the script only")
    for n, q, s in zip(NAMES, qml_uris, sh_uris):
        assert q == s, f"{n!r}: QML {q} vs script {s}"

assert "realpath -s" in script.read_text(), "the script resolves symlinks again; Gio names the path as given"
assert re.search(r'command: \["bash", "-c", \'[^\']*"\$3"', qml), "ThumbnailImage.qml: the file name is no longer passed as an argument"

print("ok: QML, the magick script and Gio name every thumbnail alike")
